version: "3"
services:
  employee-mysqldb:
    container_name: employee-mysqldb
    build:
        context: .
        dockerfile: ./db-mysql-service/Dockerfile
    ports:
      - 3306:3306
    expose:
      - 3306
    networks:
     - employee-networks
    volumes:
      - employee-mysql-volumes:/var/lib/mysql

  backend-employee-service:
    image: dinesh2016b/employee-management-system
    container_name: backend-employee-service
    build:
        context: .
        dockerfile: ./backend-employee-service/Dockerfile
    ports:
      - 8092:8092
    expose:
      - 8092
    networks:
      - employee-networks
    depends_on:
      - employee-mysqldb
    #  - backend-eureka-service

  backend-department-service:
    image: dinesh2016b/employee-management-system
    container_name: backend-department-service
    build:
        context: .
        dockerfile: ./backend-department-service/Dockerfile
    ports:
      - 8091:8091
    expose:
      - 8091
    networks:
      - employee-networks
    depends_on:
      - employee-mysqldb
    #  - backend-eureka-service

  backend-salaries-service:
    image: dinesh2016b/employee-management-system
    container_name: backend-salaries-service
    build:
        context: .
        dockerfile: ./backend-salaries-service/Dockerfile
    ports:
      - 8093:8093
    expose:
      - 8093
    networks:
      - employee-networks
    depends_on:
      - employee-mysqldb
    #  - backend-eureka-service

  backend-ems-service:
    image: dinesh2016b/employee-management-system
    container_name: backend-ems-service
    build:
        context: .
        dockerfile: ./backend-ems-service/Dockerfile
    ports:
      - 8095:8095
    expose:
      - 8095
    networks:
      - employee-networks
    #depends_on:
    #  - backend-eureka-service

  backend-eureka-service:
    image: dinesh2016b/employee-management-system
    container_name: backend-eureka-service
    build:
        context: .
        dockerfile: ./backend-eureka-service/Dockerfile
    ports:
      - 8761:8761
    expose:
      - 8761

#  employee-nginx:
#    container_name: employee-nginx
#    image: nginx
#    build:
#        context: .
#        dockerfile: ./frontend/Dockerfile
#    volumes:
#      - ./frontend/src/main/web/dist/app:/usr/share/nginx/html
#    ports:
#      - 8080:80
#    networks:
#      - employee-networks

volumes:
  employee-mysql-volumes:

networks:
  employee-networks:
