version: "3"
services:
  employee-mysqldb:
    container_name: employee-mysqldb
    build:
        context: .
        dockerfile: ./db/Dockerfile
    ports:
      - 3306:3306
    expose:
      - 3306
    networks:
     - employee-networks
    volumes:
      - employee-mysql-volumes:/var/lib/mysql

  employee-management-system-service:
    image: dinesh2016b/employee-management-system
    container_name: employee-management-system-service
    build:
        context: .
        dockerfile: ./backend/Dockerfile
    ports:
      - 8090:8090
    networks:
      - employee-networks
    depends_on:
      - employee-mysqldb

  employee-nginx:
    container_name: employee-nginx
    image: nginx
    build:
        context: .
        dockerfile: ./frontend/Dockerfile
#    volumes:
#      - ./frontend/src/main/web/dist/app:/usr/share/nginx/html
    ports:
      - 8080:80
    networks:
      - employee-networks

volumes:
  employee-mysql-volumes:

networks:
  employee-networks:
