version: "3"
services:
  employee-mysqldb:
    container_name: employee-mysqldb
    image: mysql:8
    environment:
      MYSQL_DATABASE: employees
      MYSQL_USER: root
      MYSQL_PASSWORD: Dinesh@123
      MYSQL_ROOT_PASSWORD: Dinesh@123
    ports:
      - 3306:3306
    expose:
      - 3306
    networks:
     - employee-networks
    volumes:
      - employee-mysql-volumes:/var/lib/mysql

  employee-management-system-service:
    image: dinesh2016b/employee-management-system
    container_name: employee-management-system-service
    build:
        context: .
        dockerfile: ./backend/Dockerfile
    ports:
      - 8090:8090
    networks:
      - employee-networks
    depends_on:
      - employee-mysqldb

  employee-nginx:
    container_name: employee-nginx
    image: nginx
    volumes:
      - ./frontend/src/main/web/dist/app:/usr/share/nginx/html
    ports:
      - 8070:8070
      - 443:443  
    networks:
      - employee-networks

volumes:
  employee-mysql-volumes:

networks:
  employee-networks:
