version: "3"
services:
  employee-mysql-service:
    container_name: employee-mysql-service
    image: mysql:8
    environment:
      MYSQL_DATABASE: employees
      MYSQL_USER: root
      MYSQL_PASSWORD: Dinesh@123
      MYSQL_ROOT_PASSWORD: Dinesh@123
    ports:
      - 3306:3306
    expose:
      - 3306
    networks:
       employee-mysql-networks:
    volumes:
      - employee-mysql-volumes:/var/lib/mysql

  employee-nginx:
      container_name: employee-nginx
      image: nginx
      build:
        context: .
        dockerfile: .docker/nginx.dockerfile
      volumes:
        - ./frontend/src/main/web/dist:/usr/share/nginx/html
      ports:
        - "8070:8070"
        - "443:443"
  
      networks:
        - employee-nginx-networks

  employee-management-system-service:
    image: dinesh2016b/employee-management-system
    container_name: employee-management-system-service
    build:
        context: .
        dockerfile: ./backend/Dockerfile
    ports:
      - 8090:8090
    networks:
      - employee-mysql-networks
    depends_on:
      - employee-mysql-service

volumes:
  employee-mysql-volumes:

networks:
  employee-mysql-networks:
  employee-nginx-networks:
 