version: "3"
services:
  backend-eureka-server:
    image: dinesh2016b/employee-management-system
    container_name: backend-eureka-server
    build:
        context: .
        dockerfile: ./backend-eureka-server/Dockerfile
    ports:
      - 8761:8761
    expose:
      - 8761
    networks:
     - ems-networks

  backend-zuul-api-gateway-server:
    image: dinesh2016b/employee-management-system
    container_name: backend-zuul-api-gateway-server
    build:
        context: .
        dockerfile: ./backend-zuul-api-gateway-server/Dockerfile
    ports:
      - 8765:8765
    expose:
      - 8765
    networks:
     - ems-networks

  employee-mysqldb:
    image: dinesh2016b/employee-management-system
    container_name: employee-mysqldb
    build:
        context: .
        dockerfile: ./db-mysql-service/Dockerfile
    ports:
      - 3306:3306
    expose:
      - 3306
    networks:
     - ems-networks
    volumes:
      - ems-mysql-volumes:/var/lib/mysql

  backend-department-service:
    image: dinesh2016b/employee-management-system
    container_name: backend-department-service
    build:
        context: .
        dockerfile: ./backend-department-service/Dockerfile
    ports:
      - 8091:8091
    expose:
      - 8091
    networks:
      - ems-networks
    depends_on:
      - backend-eureka-service
      - employee-mysqldb

  backend-employee-service:
    image: dinesh2016b/employee-management-system
    container_name: backend-employee-service
    build:
        context: .
        dockerfile: ./backend-employee-service/Dockerfile
    ports:
      - 8092:8092
    expose:
      - 8092
    networks:
      - ems-networks
    depends_on:
      - backend-eureka-service
      - employee-mysqldb

  backend-salaries-service:
    image: dinesh2016b/employee-management-system
    container_name: backend-salaries-service
    build:
        context: .
        dockerfile: ./backend-salaries-service/Dockerfile
    ports:
      - 8093:8093
    expose:
      - 8093
    networks:
      - ems-networks
    depends_on:
      - backend-eureka-service
      - employee-mysqldb

  backend-ems-service:
    image: dinesh2016b/employee-management-system
    container_name: backend-ems-service
    build:
        context: .
        dockerfile: ./backend-ems-service/Dockerfile
    ports:
      - 8095:8095
    expose:
      - 8095
    networks:
      - ems-networks
    depends_on:
      - backend-eureka-service

#  employee-nginx:
#    image: dinesh2016b/employee-management-system
#    container_name: employee-nginx
#    image: nginx
#    build:
#        context: .
#        dockerfile: ./frontend/Dockerfile
#    volumes:
#      - ./frontend/src/main/web/dist/app:/usr/share/nginx/html
#    ports:
#      - 8080:80
#    networks:
#      - ems-networks

volumes:
  ems-mysql-volumes:

networks:
  ems-networks:
