version: "3"
services:
  employee-mysqldb:
    container_name: employee-mysqldb
    build:
        context: .
        dockerfile: ./db/Dockerfile
    ports:
      - 3306:3306
    expose:
      - 3306
    networks:
     - employee-networks
    volumes:
      - employee-mysql-volumes:/var/lib/mysql

  employee-h2db:
    container_name: employee-h2db
    build:
        context: .
        dockerfile: ./db-h2-service/Dockerfile
    ports:
      - 3307:3307
    expose:
      - 3307
    networks:
     - employee-networks
    volumes:
      - employee-h2-volumes:/var/lib/h2

  backend-employee-service:
    image: dinesh2016b/employee-management-system
    container_name: backend-employee-service
    build:
        context: .
        dockerfile: ./backend-employee-service/Dockerfile
    ports:
      - 8091:8091
    networks:
      - employee-networks
    depends_on:
      - employee-mysqldb

  backend-department-service:
    image: dinesh2016b/employee-management-system
    container_name: backend-department-service
    build:
        context: .
        dockerfile: ./backend-department-service/Dockerfile
    ports:
      - 8092:8092
    networks:
      - employee-networks
    depends_on:
      - employee-mysqldb

  backend-salaries-service:
    image: dinesh2016b/employee-management-system
    container_name: backend-salaries-service
    build:
        context: .
        dockerfile: ./backend-salaries-service/Dockerfile
    ports:
      - 8093:8093
    networks:
      - employee-networks
    depends_on:
      - employee-mysqldb

  employee-nginx:
    container_name: employee-nginx
    image: nginx
    build:
        context: .
        dockerfile: ./frontend/Dockerfile
#    volumes:
#      - ./frontend/src/main/web/dist/app:/usr/share/nginx/html
    ports:
      - 8080:80
    networks:
      - employee-networks

volumes:
  employee-mysql-volumes:

networks:
  employee-networks:
