eureka:
  client:
    fetchRegistry: false
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://backend-eureka-server:8761/eureka
  instance:
    hostname: backend-eureka-server
server:
  port: 8761
spring:
  application:
    name: backend-eureka-server
