eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://backend-eureka-server:8761/eureka
logging:
  level:
    org:
      springframework: DEBUG
    root: ERROR
management:
  endpoints:
    web:
      exposure:
        include: '*'
server:
  error:
    include-stacktrace: never
  port: 8095
spring:
  application:
    name: backend-ems-service
  main:
    allow-bean-definition-overriding: true
