logging:
  level:
    org:
      springframework: DEBUG
    root: ERROR
management:
  endpoints:
    web:
      exposure:
        include: '*'
server:
  error:
    include-stacktrace: never
  port: 8095
  ssl:
    key-store: classpath:ems.p12
    key-store-password: dinesh
    keyStoreType: PKCS12
spring:
  application:
    name: backend-ems-service
