logging:
  level:
    org:
      springframework: DEBUG
    root: ERROR
server:
  error:
    include-stacktrace: never
  port: 8091
  ssl:
    key-store: classpath:ems.p12
    key-store-password: dinesh
    keyStoreType: PKCS12
spring:
  application:
    name: backend-department-service
  datasource:
    driverClassName: org.h2.Driver
    initialization-mode: always
    password: admin
    url: jdbc:h2:mem:employees
    username: admin
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: false
