eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://backend-eureka-server:8761/eureka
logging:
  level:
    org:
      springframework: DEBUG
    root: ERROR
management:
  endpoints:
    web:
      exposure:
        include: '*'
server:
  error:
    include-stacktrace: never
  port: 8093
spring:
  application:
    name: backend-salaries-service
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    password: Dinesh@123
    url: jdbc:mysql://employee-mysqldb:3306/employees
    username: root
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: false
  main:
    allow-bean-definition-overriding: true
